FROM python:2.7
MAINTAINER Potato Powered Software <support@potatopowered.net>

# install sphinx and the themes/domains we use
RUN pip install sphinx 
RUN pip install sphinx-autobuild 
RUN pip install sphinx_rtd_theme 
RUN pip install sphinxcontrib-phpdomain
RUN pip install sphinx_rtd_theme

WORKDIR /data